package game

import (
	"math/rand/v2"
	"strings"
)

// answers is the pool of words the game picks from.
// Kept moderate — common, well-known five-letter words.
var answers = []string{
	"about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
	"after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
	"alien", "align", "alike", "alive", "alley", "allow", "alone", "along",
	"alter", "ample", "angel", "anger", "angle", "angry", "anime", "ankle",
	"apart", "apple", "apply", "arena", "argue", "arise", "armor", "aroma",
	"aside", "asset", "audio", "avoid", "awake", "award", "aware", "awful",
	"baker", "basic", "basin", "basis", "beach", "begin", "being", "bench",
	"berry", "birth", "black", "blade", "blame", "bland", "blank", "blast",
	"blaze", "bleed", "blend", "blind", "block", "blood", "bloom", "blown",
	"board", "bonus", "booth", "bound", "brain", "brand", "brave", "bread",
	"break", "breed", "brick", "brief", "bring", "broad", "broke", "brown",
	"brush", "build", "bunch", "burst", "buyer", "cabin", "cable", "candy",
	"cargo", "carry", "catch", "cause", "chain", "chair", "chalk", "chaos",
	"charm", "chart", "chase", "cheap", "check", "cheek", "cheer", "chest",
	"chief", "child", "chill", "china", "chunk", "civic", "civil", "claim",
	"clash", "class", "clean", "clear", "click", "cliff", "climb", "cling",
	"clock", "clone", "close", "cloth", "cloud", "coach", "coast", "color",
	"comet", "comic", "coral", "couch", "count", "court", "cover", "crack",
	"craft", "crane", "crash", "crazy", "cream", "creek", "crime", "crisp",
	"cross", "crowd", "crown", "cruel", "crush", "curve", "cycle", "daily",
	"dance", "death", "debug", "delay", "delta", "dense", "depth", "derby",
	"devil", "diary", "dirty", "dizzy", "donor", "doubt", "dough", "draft",
	"drain", "drake", "drama", "drank", "drawn", "dream", "dress", "drift",
	"drill", "drink", "drive", "drone", "drove", "drown", "dying", "eager",
	"eagle", "early", "earth", "eight", "elder", "elect", "elite", "email",
	"empty", "enemy", "enjoy", "enter", "entry", "equal", "error", "essay",
	"event", "every", "exact", "exile", "exist", "extra", "faint", "fairy",
	"faith", "false", "fancy", "fatal", "fault", "feast", "fence", "ferry",
	"fever", "fiber", "field", "fight", "final", "first", "flame", "flash",
	"fleet", "flesh", "float", "flood", "floor", "flora", "flour", "fluid",
	"flush", "focal", "focus", "force", "forge", "forth", "found", "frame",
	"frank", "fraud", "fresh", "front", "frost", "fruit", "fully", "funny",
	"giant", "given", "gland", "glass", "globe", "gloom", "glory", "glove",
	"going", "grace", "grade", "grain", "grand", "grant", "grape", "grasp",
	"grass", "grave", "great", "green", "greet", "grief", "grill", "grind",
	"groan", "gross", "group", "grove", "grown", "guard", "guess", "guest",
	"guide", "guilt", "habit", "happy", "harsh", "haste", "haven", "heart",
	"heavy", "hedge", "hello", "hence", "honey", "honor", "horse", "hotel",
	"house", "human", "humor", "ideal", "image", "imply", "index", "indie",
	"inner", "input", "Irish", "issue", "ivory", "jelly", "jewel", "joint",
	"joker", "judge", "juice", "karma", "knife", "knock", "known", "label",
	"lance", "large", "laser", "later", "laugh", "layer", "learn", "lease",
	"leave", "legal", "lemon", "level", "light", "limit", "linen", "liver",
	"local", "lodge", "logic", "lonely", "loose", "lover", "lower", "loyal",
	"lucky", "lunch", "lying", "magic", "major", "maker", "manor", "maple",
	"march", "match", "maybe", "mayor", "meant", "media", "mercy", "merit",
	"metal", "meter", "might", "minor", "minus", "model", "money", "month",
	"moral", "motor", "mount", "mouse", "mouth", "movie", "music", "naive",
	"nerve", "never", "night", "noble", "noise", "north", "noted", "novel",
	"nurse", "ocean", "offer", "olive", "onset", "opera", "orbit", "order",
	"other", "outer", "owner", "oxide", "ozone", "panic", "patch", "pause",
	"peace", "pearl", "penny", "phase", "phone", "photo", "piano", "pilot",
	"pitch", "pixel", "pizza", "place", "plain", "plane", "plant", "plate",
	"plaza", "plead", "pluck", "plumb", "point", "polar", "pound", "power",
	"press", "price", "pride", "prime", "print", "prior", "prize", "probe",
	"prone", "proof", "proud", "prove", "psalm", "purse", "queen", "query",
	"quest", "queue", "quick", "quiet", "quota", "quote", "radar", "radio",
	"raise", "rally", "ranch", "range", "rapid", "ratio", "reach", "react",
	"ready", "realm", "rebel", "refer", "reign", "relax", "reply", "rider",
	"ridge", "rifle", "right", "rigid", "rival", "river", "robin", "robot",
	"rocky", "rouge", "rough", "round", "route", "royal", "rugby", "ruler",
	"rural", "salad", "sauce", "scale", "scene", "scope", "score", "sense",
	"serve", "setup", "seven", "shade", "shake", "shall", "shame", "shape",
	"share", "shark", "sharp", "shelf", "shell", "shift", "shine", "shirt",
	"shock", "shore", "short", "shout", "sight", "sigma", "silly", "since",
	"sixth", "sixty", "skate", "skill", "skull", "slash", "slate", "sleep",
	"slice", "slide", "slope", "smart", "smell", "smile", "smoke", "snake",
	"solar", "solid", "solve", "sonic", "sorry", "south", "space", "spare",
	"speak", "speed", "spend", "spice", "spike", "spine", "spite", "split",
	"spoke", "sport", "spray", "squad", "stack", "staff", "stage", "stain",
	"stake", "stall", "stamp", "stand", "stare", "stark", "start", "state",
	"stave", "steal", "steam", "steel", "steep", "steer", "stern", "stick",
	"stiff", "still", "stock", "stone", "stood", "store", "storm", "story",
	"stout", "stove", "strip", "stuck", "study", "stuff", "style", "sugar",
	"suite", "super", "surge", "swamp", "swear", "sweep", "sweet", "swift",
	"swing", "swirl", "sword", "swore", "sworn", "syrup", "table", "taste",
	"teach", "teeth", "tempo", "thank", "theme", "thick", "thing", "think",
	"third", "those", "three", "threw", "throw", "thumb", "tiger", "tight",
	"timer", "tired", "title", "today", "token", "total", "touch", "tough",
	"towel", "tower", "toxic", "trace", "track", "trade", "trail", "train",
	"trait", "trash", "treat", "trend", "trial", "tribe", "trick", "tried",
	"troop", "truck", "truly", "trump", "trunk", "trust", "truth", "tumor",
	"tuner", "twice", "twist", "ultra", "uncle", "under", "unify", "union",
	"unite", "unity", "until", "upper", "upset", "urban", "usage", "usual",
	"valid", "value", "valve", "vapor", "venue", "verse", "video", "vigor",
	"viral", "virus", "visit", "vital", "vivid", "vocal", "vodka", "voice",
	"voter", "wage", "wagon", "waste", "watch", "water", "weave", "weigh",
	"weird", "whale", "wheat", "wheel", "where", "which", "while", "white",
	"whole", "whose", "witch", "women", "world", "worry", "worse", "worst",
	"worth", "would", "wound", "wrath", "write", "wrote", "yacht", "yield",
	"young", "youth", "zebra",
}

// validGuesses includes common five-letter words that are acceptable
// guesses but aren't in the answer pool. Combined with answers,
// this gives a much larger dictionary for validation.
var validGuesses = []string{
	"acids", "acres", "added", "admit", "aged", "aided", "aimed", "aired",
	"album", "alert", "algae", "alien", "align", "aloud", "amber", "amend",
	"amino", "angel", "angle", "antic", "anvil", "apply", "arena", "arise",
	"array", "arrow", "asset", "atlas", "attic", "avoid", "axiom", "badge",
	"badly", "bagel", "baron", "batch", "began", "being", "below", "berry",
	"bigot", "biker", "bingo", "birch", "birth", "bison", "bloom", "blown",
	"bluff", "blunt", "blurt", "bogus", "bonus", "booze", "botch", "boxer",
	"brace", "braid", "brake", "brash", "bravo", "brawn", "briar", "bribe",
	"brink", "brisk", "broth", "brunt", "budge", "buggy", "bulge", "bumpy",
	"bunny", "buyer", "byway", "cadet", "camel", "candy", "carat", "cargo",
	"carol", "cedar", "cheap", "cheek", "chess", "chick", "chili", "chimp",
	"chirp", "choir", "chose", "chump", "chunk", "cider", "cigar", "cinch",
	"civic", "clamp", "clang", "clank", "clasp", "claw", "clerk", "cliff",
	"cling", "cloak", "clone", "cloth", "cloud", "clown", "cobra", "cocoa",
	"coils", "colic", "colon", "comic", "conch", "coral", "corps", "couch",
	"cough", "coupe", "coypu", "cramp", "crank", "craps", "crawl", "craze",
	"creed", "creep", "crest", "crick", "crimp", "croak", "crock", "cromp",
	"cross", "crowd", "crude", "crust", "cubic", "decal", "decor", "decoy",
	"deity", "delve", "denim", "depot", "derby", "detox", "digit", "ditto",
	"dodge", "doing", "donor", "dowdy", "drawl", "dread", "drool", "druid",
	"drunk", "dryer", "dryly", "dunce", "dwarf", "dwell", "eater", "edict",
	"eight", "elfin", "elbow", "elite", "elope", "elude", "ember", "emoji",
	"emote", "endow", "envoy", "epoch", "equip", "erode", "erupt", "ethic",
	"evade", "exalt", "excel", "exert", "expat", "extol", "extra", "exude",
	"facet", "faint", "fairy", "farce", "fatty", "fauna", "feast", "femur",
	"ferry", "fetch", "fetid", "fetus", "fiber", "fiery", "filth", "finch",
	"fizzy", "fjord", "flail", "flair", "flask", "flats", "flaxy", "fella",
	"flick", "fling", "flint", "flirt", "flock", "floss", "flout", "flowy",
	"fluff", "fluke", "flung", "flunk", "flush", "flute", "foamy", "foggy",
	"folly", "forge", "forgo", "forte", "forum", "found", "fowl", "frail",
	"freak", "freed", "friar", "frizz", "frond", "froze", "frugal", "fully",
	"fungi", "funky", "fuzzy", "gamer", "gauge", "gaunt", "gavel", "geeky",
	"getup", "ghoul", "giddy", "girth", "gizmo", "gland", "glare", "gleam",
	"glide", "glint", "gloat", "gloss", "glyph", "gnome", "golem", "goofy",
	"gouge", "gourd", "graft", "grasp", "graze", "greed", "grief", "grime",
	"grimy", "gripe", "grits", "groin", "groom", "grope", "gross", "growl",
	"grunt", "guild", "guise", "gulch", "gully", "gumbo", "gusto", "gusty",
	"gypsy", "haven", "hazel", "heady", "heave", "hedge", "hefty", "helix",
	"hitch", "hoard", "hobby", "homer", "hound", "hover", "howdy", "huffy",
	"humid", "hutch", "hyena", "idiom", "idiot", "igloo", "image", "impel",
	"inane", "incur", "inept", "inert", "infer", "ingot", "inlet", "input",
	"intel", "inter", "intro", "ionic", "irate", "ivory", "jazzy", "jelly",
	"jewel", "jiffy", "joist", "jolly", "joust", "jumbo", "jumpy", "juror",
	"kayak", "kebab", "kinky", "kiosk", "knack", "knead", "kneel", "knelt",
	"knack", "known", "koala", "kraft", "kudos", "labor", "lance", "lapse",
	"larch", "largo", "larva", "latch", "lathe", "ledge", "leech", "legal",
	"leggy", "lemur", "level", "lever", "libel", "lilac", "limbo", "lingo",
	"llama", "lobby", "lofty", "login", "lotus", "lousy", "lucid", "lumen",
	"lunar", "lunch", "lunge", "lusty", "lying", "lymph", "lyric", "macho",
	"macro", "mafia", "manga", "mango", "manly", "manor", "marsh", "mason",
	"maxim", "mealy", "melee", "melon", "metro", "micro", "middy", "midst",
	"mimic", "mince", "mirth", "mocha", "moist", "moldy", "money", "monks",
	"moody", "moose", "moped", "moral", "morph", "mossy", "motel", "motif",
	"motto", "mourn", "mousy", "mover", "moxie", "mucus", "muddy", "mulch",
	"mummy", "mural", "murky", "mushy", "muted", "nacho", "naive", "nanny",
	"nasal", "nasty", "naval", "nerdy", "newly", "nicer", "nifty", "ninja",
	"nitro", "noisy", "nomad", "notch", "nudge", "nylon", "obese", "occur",
	"oddly", "offal", "omega", "onset", "optic", "orbit", "organ", "other",
	"otter", "ought", "ounce", "outdo", "outer", "ovary", "oxide", "ozone",
	"padre", "pagan", "paint", "panda", "panel", "panic", "pansy", "pants",
	"paper", "party", "paste", "pasta", "patio", "peach", "pedal", "perch",
	"peril", "perky", "pesky", "pesto", "petty", "pixel", "pixie", "plaid",
	"plank", "plate", "plaza", "plead", "pleat", "plier", "pluck", "plumb",
	"plume", "plump", "plush", "poach", "poker", "polar", "polka", "polyp",
	"pooch", "poppy", "porch", "poser", "posit", "posse", "pouch", "pouty",
	"prank", "prawn", "preen", "prism", "privy", "prowl", "proxy", "prude",
	"prune", "psalm", "pudgy", "pulpy", "punch", "pupal", "pupil", "puppy",
	"purge", "pushy", "pygmy", "qualm", "quart", "quasi", "queen", "queer",
	"query", "queue", "quick", "quill", "quirk", "quota", "rabbi", "radar",
	"rainy", "rally", "ramen", "ranch", "randy", "range", "raven", "rayon",
	"realm", "rebel", "rebus", "recap", "decoy", "redux", "reedy", "reign",
	"relax", "remit", "repay", "repel", "resin", "retro", "rhyme", "rigid",
	"rigor", "rinse", "risen", "risky", "rival", "rivet", "roast", "robin",
	"robot", "rocky", "rodeo", "rogue", "roost", "rouge", "rover", "rowdy",
	"royal", "ruddy", "rumba", "rumor", "rupee", "rusty", "sadly", "saint",
	"salsa", "sandy", "saner", "sappy", "satin", "sauce", "sauna", "savor",
	"savvy", "scald", "scalp", "scant", "scare", "scarf", "scene", "scent",
	"scone", "scoop", "scope", "score", "scorn", "scout", "scram", "scrap",
	"scrub", "sedan", "seize", "sense", "serum", "serve", "setup", "seven",
	"sever", "shack", "shady", "shaft", "shale", "shame", "shank", "shape",
	"shard", "shave", "shawl", "sheaf", "sheen", "sheer", "sheet", "shelf",
	"shell", "shift", "shire", "shrub", "shrug", "siege", "sieve", "sigma",
	"since", "siren", "sissy", "sixth", "sixty", "skate", "skimp", "skirt",
	"skull", "skunk", "slack", "slain", "slang", "slash", "sleet", "slept",
	"slice", "slick", "slide", "slime", "slimy", "sling", "slink", "slope",
	"sloth", "slump", "slung", "slurp", "smack", "small", "smart", "smash",
	"smear", "smell", "smile", "smirk", "smite", "smoke", "snack", "snail",
	"snare", "snarl", "sneak", "sneer", "snide", "sniff", "snore", "snout",
	"soggy", "solar", "solve", "sonic", "sorry", "south", "space", "spade",
	"spark", "spawn", "spear", "speck", "spell", "spelt", "spent", "spice",
	"spied", "spill", "spine", "spoke", "spoof", "spook", "spool", "spoon",
	"spore", "sport", "spray", "spree", "sprig", "spunk", "staid", "stain",
	"stair", "stake", "stale", "stalk", "stall", "stamp", "stand", "stank",
	"stare", "stark", "start", "stash", "state", "stave", "stays", "steak",
	"steal", "steam", "steed", "steel", "steep", "steer", "stern", "stiff",
	"still", "sting", "stink", "stock", "stoic", "stoke", "stole", "stomp",
	"stone", "stood", "stool", "stoop", "store", "stork", "story", "stout",
	"stove", "strap", "straw", "stray", "strip", "strut", "stuck", "study",
	"stuff", "stump", "stung", "stunk", "stunt", "style", "suave", "sugar",
	"suite", "sulky", "sunny", "super", "surge", "sushi", "swamp", "swarm",
	"swear", "sweat", "sweep", "sweet", "swept", "swift", "swill", "swine",
	"swing", "swipe", "swirl", "swish", "swoon", "swoop", "sword", "swore",
	"sworn", "swung", "syrup", "tabby", "table", "tacit", "taffy", "taint",
	"tally", "talon", "tango", "tangy", "tapir", "tardy", "taste", "taunt",
	"tawny", "teach", "teeth", "tempo", "tense", "tepid", "thick", "thief",
	"thigh", "thing", "think", "thorn", "those", "three", "threw", "throw",
	"thrum", "thumb", "thump", "tiara", "tidal", "tiger", "tight", "timer",
	"tipsy", "titan", "title", "toast", "today", "token", "total", "totem",
	"touch", "tough", "towel", "tower", "toxic", "track", "trade", "trail",
	"train", "trait", "tramp", "trash", "trawl", "treat", "trend", "triad",
	"trial", "tribe", "trick", "tried", "trill", "tripe", "trite", "troll",
	"troop", "troth", "trout", "truce", "truck", "truly", "trunk", "trust",
	"truth", "tulip", "tumor", "tuner", "tunic", "turbo", "tutor", "tweed",
	"twice", "twine", "twirl", "twist", "tying", "udder", "ulcer", "ultra",
	"uncle", "uncut", "under", "undue", "undid", "unfit", "unify", "union",
	"unite", "unity", "unlit", "until", "unwed", "upper", "upset", "urban",
	"usher", "using", "usual", "utter", "vague", "valid", "value", "valve",
	"vapid", "vault", "vegan", "veiny", "venom", "venue", "verge", "verse",
	"vicar", "video", "vigor", "vinyl", "viola", "viper", "viral", "virus",
	"visit", "visor", "vista", "vital", "vivid", "vocal", "vodka", "vogue",
	"voice", "voter", "vouch", "vowel", "vulva", "wacky", "wagon", "waist",
	"waste", "watch", "water", "waver", "weary", "weave", "wedge", "weedy",
	"weigh", "weird", "whale", "wheat", "wheel", "where", "which", "whiff",
	"while", "whine", "whirl", "whisk", "white", "whole", "whose", "widen",
	"widow", "width", "wield", "windy", "witch", "women", "woods", "woody",
	"world", "worry", "worse", "worst", "worth", "would", "wound", "woven",
	"wrack", "wrath", "wreak", "wreck", "wring", "wrist", "write", "wrong",
	"wrote", "yacht", "yearn", "yeast", "yield", "young", "youth", "zebra",
	"zesty", "zippy", "zombi", "zonal",
}

var allValidWords map[string]bool

func init() {
	allValidWords = make(map[string]bool, len(answers)+len(validGuesses))
	for _, w := range answers {
		allValidWords[strings.ToLower(w)] = true
	}
	for _, w := range validGuesses {
		allValidWords[strings.ToLower(w)] = true
	}
}

func RandomWord() string {
	return answers[rand.IntN(len(answers))]
}

func IsValidWord(word string) bool {
	return allValidWords[strings.ToLower(word)]
}
